---
title: "Workshop3-RMarkdown"
author: "Himanshi"
date: '2022-03-01'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

### Data Wrangling

```{r}

#data loading

survey<-read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-18/survey.csv')

country<-survey%>%distinct(country)

survey%>%count(country, sort=TRUE)

survey_short<-survey%>%
  filter(
    country=="United States" |
      country=="USA" |
      country=="US" |
      country=="U.S." |
      country=="United States of America" |
      country=="Usa"
  )
  
survey_short%>%filter(
  annual_salary>50000 & 
    gender=="Woman"
  )
```
#data wrangling
Arranging observations


```{r}
survey_short%>%
  head(10)

 select(timestamp,how_old_are_you,job_title)%>%
  knitr::
  kable(survey_short[1:10,1:5])
 
 survey_short%>% top_n(n=10)
 
 survey_short%>%arrange(desc(annual_salary))%>%
   select(industry,annual_salary)
 
 survey_short%>%count(industry, sort=TRUE)
 
 
```

groupings and new variables

```{r}
survey_short%>%
  mutate(total_salary=annual_salary+other_monetary_comp)%>%
  select(industry,total_salary,annual_salary,other_monetary_comp)

survey_short%>%
  mutate(average_salary=mean(annual_salary, na.rm=TRUE))%>%
  select(industry,average_salary)

survey_short%>%
  group_by(industry)%>%
  mutate(average_salary=mean(annual_salary, na.rm=TRUE))%>%
  arrange(desc(average_salary))%>%
  ungroup()

survey_short%>%
  group_by(industry,gender)%>%
  mutate(average_salary=mean(annual_salary, na.rm=TRUE))%>%
  select(industry,gender,average_salary)%>%
  arrange(desc(average_salary))%>%
  ungroup()

#add a new variable max_salary which is maximum salary per industry

max_salary<-survey_short%>%
  mutate(max_salary=max(annual_salary, na.rm=TRUE))


```

#summarizing data

```{r}
survey_short%>%
  group_by(industry)%>%
  summarise(average_salary=mean(annual_salary, na.rm=TRUE))

#group by industry and gender and use summarise for average salary

#group by gender and industry and use summarise for average salary

#group by industry and gender and use summarise for average salary and max salary

survey_short%>%
  group_by(industry,gender)%>%
  summarise(average_salary=mean(annual_salary, na.rm=TRUE))

survey_short%>%
  group_by(gender,industry)%>%
  summarise(average_salary=mean(annual_salary, na.rm=TRUE))


```

```{r}
survey_short%>%
  group_by(industry,gender)%>%
  summarise(
    average_salary=mean(annual_salary, na.rm=TRUE),
    max_salary=max(annual_salary, na.rm=TRUE)
  )
```
case_when

```{r}
survey_short_veryshort<-survey_short%>%
  select(industry,gender,annual_salary)

#if annual_salary is more than 70000 then your annual_salary_level is high otherwise it i low

survey_short_veryshort%>%
  mutate(
    annual_salary_level=case_when(annual_salary>70000 ~"high", T~"low")
  )%>%
  arrange(desc(annual_salary))

#if annual_salary is more than 70000 then your annual_salary_level is high, if annual salary less or equal to 70000 then your annual_salary_level is middle otherwise it is low

survey_short_veryshort%>%
  mutate(annual_salary_level=case_when(annual_salary>700000 ~"high",annual_salary>70000 & annual_salary<=700000 ~"middle", T~"low"))%>%
  arrange(desc(annual_salary))

#create a variable highly_paid_women
#if gender=="woman" and annual_salary>500000 then (~)it is high, otherwise it is low

survey_short_veryshort%>%
  mutate(high_paid_wom=case_when(gender=="Woman" & annual_salary>50000~"high", T~"low"))%>%
  arrange(desc(annual_salary))
```







